version: '3.8'

services:
  nextjs:
    build: 
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - hapi
    environment:
      - NEXT_PUBLIC_HAPI_API_URL=http://hapi:3001

  hapi:
    build: 
      context: ./backend
    ports:
      - "3001:3001"
