version: "3.8"

services:
  nextjs:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - hapi
    environment:
      - NEXT_PUBLIC_HAPI_API_URL=http://hapi:4000

  hapi:
    build:
      context: ./backend
    ports:
      - "4000:4000"
